language: ruby
cache: bundler

sudo: false

before_install:
  - gem update --system 2.7.10
  - gem update bundler

# before_script:
#   - if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1.17.0

script:
  - bundle exec rspec

notifications:
  email: false
